<!DOCTYPE html>
<head>
    <meta name="author" content="Rafał Mańka">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <?php echo $this->headTitle('Fiszki API'); ?>
    <?php  // setting content type and character set
           $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'en-US'); ?>
    <?php // disabling client-side cache
            $this->headMeta()
                ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
                ->appendHttpEquiv('pragma', 'no-cache')
                ->appendHttpEquiv('Cache-Control', 'no-cache');?>
    <?php $this->headMeta()->appendName('keywords', 'fiszki, nauka angielskiego, języki obce'); ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/js.js'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/css.css');  ?>
</head>
<body class="no-sidebar">
<header role="banner">
    <figure class="logo">
        <a href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ;?>"/>
    </figure>
    <hgroup>
        <h1><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index')) ;?>">Fiszki</a></h1>
        <h2>Strona internetowa służąca jako uzupełnienie aplikacji na system Android</h2>
    </hgroup>
    <nav>
        <ul id="navigation">
            <li><a href="<?php echo $this->url(array('controller'=>'parse','action'=>'index')) ;?>">Dodaj</a></li>
            <li><a href="<?php echo $this->url(array('controller'=>'api','action'=>'index')).'/fetchLanguages' ?>">API</a></li>
            <li><a href="#">Item 3</a></li>
        </ul>
    </nav>
</header>
<div id="main">
    <div id="content">
        <div class="blog-index">
            <article>
                <?php echo $this->layout()->content; ?>
            </article>
        </div>
    </div>
</div>
</body>
</html>


